### ISSUE TITLE
[META] Byzantium Implementation Progress

### ISSUE THREAD

**Issue by jwasinger** [ethereumjs/ethereumjs-vm#209]
# Overview
Implementation of all Byzantium EIPs is complete with the exception of the following failing tests that will be fixed before release:
### Failing Blockchain Tests

- ~~uncleBloomNot0~~
- ~~futureUncleTimestampDifficultyDrop~~
- ~~uncleHeaderAtBlock2~~
- ~~futureUncleTimestamp2~~

### Failing State Tests

- ~~randomStatetest642~~ (fix after ``master`` release)

## Planned release date: Monday, 9/25/2017

Merge on ``master``, ``npm`` release after a couple of days testing.

## Summary of Changes to EthereumJS Libraries

- [ethereumjs-vm](https://github.com/ethereumjs/ethereumjs-vm) - https://github.com/ethereumjs/ethereumjs-vm/pull/161
    * [x] EIP 649 (Difficulty bomb delay)
    * [x] EIP 140
    * [x] EIP 196
    * [x] EIP 197
    * [x] EIP 198
    * [x] EIP 211
    * [x] EIP 214
    * [x] EIP 658
- [ethereumjs-block](https://github.com/ethereumjs/ethereumjs-block) - https://github.com/ethereumjs/ethereumjs-block/pull/32
    * [x] EIP 100
- [rustbn.js](https://github.com/ethereumjs/rustbn.js) Initial version (v0.1.0 ?) (https://github.com/ethereumjs/rustbn.js/pull/2)
- [ethereumjs/common](https://github.com/ethereumjs/common) -https://github.com/ethereumjs/common/pull/6
    * [x] EIP 649 (Block reward reduction)

## Miscellaneous TODOs

- [x] Remove left-over ``console.log`` statements
- [x] Test the examples in ``examples`` folder
- [x] Check the ``README`` API documentation
- [x] Add library changes to ``Unreleased`` section in ``CHANGELOG``
- [ ] Release dependency ``master`` branch versions, update ``package.json``

## EthereumJS Library Updates

- [x] [ethereumjs-vm](https://github.com/ethereumjs/ethereumjs-vm) v2.2.2 -> v.2.3.1 https://github.com/ethereumjs/ethereumjs-vm/pull/216
- [x] [ethereumjs-block](https://github.com/ethereumjs/ethereumjs-block) v1.6.1 -> v1.7.0 (EIP100 / EIP 649) https://github.com/ethereumjs/ethereumjs-block/pull/37
- [x] [rustbn.js](https://github.com/ethereumjs/rustbn.js) Initial version v0.1.0 https://github.com/ethereumjs/rustbn.js/pull/6
- [x] [ethereumjs/common](https://github.com/ethereumjs/common) v0.1.0 -> 0.2.0 (block reward / gas costs) https://github.com/ethereumjs/common/pull/9
- [x] [ethereumjs-blockchain](https://github.com/ethereumjs/ethereumjs-blockchain) v2.0.2 -> 2.1.0 https://github.com/ethereumjs/ethereumjs-blockchain/pull/36

Please merge in the following order (wait for tests in-between, eventually re-trigger build):

(common, rustbn.js) -> ethereumjs-block -> ethereumjs-blockchain -> ethereumjs-vm
