### ISSUE TITLE
Separate API Tests for the VM

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#310]
**Introduction / Situation**

In the current [tests](https://github.com/ethereumjs/ethereumjs-vm/tree/master/tests) setup only the official Ethereum state and blockchain [tests](https://github.com/ethereum/tests) are run to test the VM functionality.

This gives a good impression of the current state of compatibility towards the latest HF changes but leaves the outer API of the library more-or-less untested, see the red files in one of the latest [coverage reports](https://coveralls.io/github/ethereumjs/ethereumjs-vm).

This is simply not sufficient, since this currently means that various possible invocations of the API (instantiation with or without ``blockchain``,...) as well as larger parts of the non-VM-executing code parts remain completely untested, see e.g. the poor coverage for the ``runBlock.js`` file (< 20%, *sigh*).

**Task Description**

This can be tackled by adding a second test suite and setup, resembling more traditional tests like e.g. in the [block](https://github.com/ethereumjs/ethereumjs-block/blob/master/tests/block.js) library (super-random example, don't go along too closely) and testing the different instantiation and execution paths for the VM.

Like always with tests even a very basic test setup with just a handful of tests would already make a huge difference and prevent issues like https://github.com/ethereumjs/ethereumjs-vm/issues/303 where functionality completely broke and no one noticed.

On a side note: Beside improve test coverage and library quality this will also have the benefit of giving a comprise and up-to-date overview on library usage and instantiation, since our [examples](https://github.com/ethereumjs/ethereumjs-vm/tree/master/examples) have a tendency to always be out-of-date.

**Goals**

A suite of initially maybe 15-20 additional tests - e.g. in ``tests/api/`` should be developed which tests:

- At least 2-3 additional instantiation paths of the ``VM`` in [index.js](https://coveralls.io/builds/17945610/source?filename=lib/index.js)
- Larger parts of [runBlockchain.js](https://coveralls.io/builds/17945610/source?filename=lib/runBlockchain.js)
- Larger parts of [runBlock.js](https://coveralls.io/builds/17945610/source?filename=lib/runBlock.js)
- 1-2 new instantiation paths in [runTx.js](https://coveralls.io/builds/17945610/source?filename=lib/runTx.js)
- Additional parts of [bloom.js](https://coveralls.io/builds/17945610/source?filename=lib/bloom.js), [fakeBlockChain.js](https://coveralls.io/builds/17945610/source?filename=lib/fakeBlockChain.js), [runJit.js](https://coveralls.io/builds/17945610/source?filename=lib/runJit.js) (scope to be determined)
- ``StateManager`` is under refactoring so not too much emphasis on this, maybe 1-2 tests to start would be nevertheless good

Generally the setup of a high-quality test structure with non-code repetition, utility functions and eventually good structured test data has precedence over the amount and extent of tests or coverage.

**Skills**

For taking on this issue a solid understanding of the internal working of the Ethereum VM and some broader picture of the execution process within a blockchain environment is needed.

Generally this should be a really rewarding task since this will frankly lead to a deeper understanding of the various parts of the VM on tackling.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 440.0 DAI (440.0 USD @ $1.0/DAI) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/781).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $22,730.94 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 440.0 DAI (440.0 USD @ $1.0/DAI) attached to this issue has been **cancelled** by the bounty submitter__

 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $22,290.94 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by s1na** [comment]
@holgerd77 I would be interested in tackling this, specially because I'm hoping to work on ewasm later on and this task would increase my understanding of the vm by quite a bit. However, I'm not deeply familiar with inner workings of the vm as of yet. Is it okay if I give it a try? or this is a high-priority task which should be done asap?

**Comment by holgerd77** [comment]
@s1na It is that sense "high-priority" that it should meet certain quality standards at the end, this is not super time-critical though. If you have got some experience in writing tests and think that you close enough with your understanding of the broader ecosystem that encircling this specific field is not too hard, go ahead and give it a try, looking forward to it! 😄 

Will to some extend be there for some help if you are in need, do have to level down work in the coming weeks though due to personal reasons.

**Comment by s1na** [comment]
@holgerd77 Okay, I will then try to create a PR early, so that with your helpful comments in the review I can hopefully satisfy the standards :)

**Comment by gitcoinbot** [comment]
@s1na Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=1) | [3 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=3) | [5 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=5) | [10 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=10) | [100 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=100)

**Comment by vs77bb** [comment]
Thanks for the heads up @s1na - have fun at dappcon! Say hi to @ceres_station / @mbeacom if you see them 😄

**Comment by holgerd77** [comment]
@s1na @vs77bb Ah, you're already in social exchange, great 😄! Enjoy dappcon, can't be there unfortunately!

**Comment by mkosowsk** [comment]
Hi @s1na, just a friendly check-in here 😀 have you had a chance to take a look at this issue? 👍

**Comment by s1na** [comment]
Hey @mkosowsk :) I'm tackling the issue [here](https://github.com/ethereumjs/ethereumjs-vm/pull/315).

**Comment by mkosowsk** [comment]
@s1na thanks! Will keep my eyes peeled, just wanted to make sure that you got paid out as soon as your work is accepted! 👍👍👍

**Comment by Thoughtscript** [comment]
Hi! Just checking to see if there's any work on this that still needs doing! Thanks!

**Comment by gitcoinbot** [comment]
@s1na Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=1) | [3 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=3) | [5 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=5) | [10 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=10) | [100 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=100)

**Comment by s1na** [comment]
@gitcoinbot Hi :) Yes, I'm still working on the issue.

**Comment by gitcoinbot** [comment]
@s1na Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=1) | [3 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=3) | [5 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=5) | [10 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=10) | [100 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=100)

**Comment by s1na** [comment]
@gitcoinbot yep :)

**Comment by gitcoinbot** [comment]
@s1na Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=1) | [3 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=3) | [5 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=5) | [10 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=10) | [100 days](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782?snooze=100)

**Comment by s1na** [comment]
Hey @gitcoinbot, yes I'm still working on the issue :)

**Comment by vs77bb** [comment]
Hi @s1na I know you've been moving this along. Mind letting us know what's left in order for the bounty to be claimed? cc @holgerd77 for his context, as well 👍

**Comment by s1na** [comment]
Hey @vs77bb, thanks for following the progress :) to my knowledge, I should extract 2 more PRs out of #315 for review, in addition to #352 which is close to being merged I think.

**Comment by holgerd77** [comment]
Hi @vs77bb, thanks for following up on this. I was somewhat slow with reviewing in the last weeks due to family reasons + Sina did a lot more than what I expected to be done for this bounty. 😄 

Nevertheless I also had the thought a couple of days ago, that we should really come to a close on this one, maybe we can start a follow-up bounty with some more tests, but that's on another plate.

I will have somewhat more time in the coming 2-3 weeks and will also prioritize reviewing the last 2 PRs. Thanks for making this possible, this work is really substantially contributing to sustain and improve the quality of our VM code!

**Comment by holgerd77** [comment]
Hi @vs77bb Vivek, this is now completed and @s1na did a great work on this, can we have a bounty payout here? Is there anything I need to do for this to be processed?

**Comment by ceresstation** [comment]
Hey @s1na can you submit work on this? I'll pay you out as soon as that's done!

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 340.0 DAI (340.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@s1na](https://gitcoin.co/profile/s1na)



@ceresstation please take a look at the submitted work:
* (Link Not Provided) by @s1na

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $25,872.10 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 340.0 DAI (340.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @s1na.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereumjs/ethereumjs-vm/310/782)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $25,632.10 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
