### ISSUE TITLE
Constantinople Implementation Progress

### ISSUE THREAD

**Issue by jwasinger** [ethereumjs/ethereumjs-vm#322]
The following EIPs need to be implemented for EthereumJSVM to be compatible with the upcoming Constantinople hardfork:

* [X] [EIP 145](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md) bitwise: https://github.com/ethereumjs/ethereumjs-vm/pull/251
* [ ] [EIP 1014](https://github.com/ethereum/EIPs/pull/1014) CREATE2: [work in progress](https://github.com/ethereumjs/ethereumjs-vm/pull/329)
* [ ] [EIP 1052](https://eips.ethereum.org/EIPS/eip-1052) EXTCODEHASH: [work in progress](https://github.com/ethereumjs/ethereumjs-vm/pull/326)
* [ ] [EIP 1283](https://eips.ethereum.org/EIPS/eip-1283) SSTORE net metering without dirty maps (replaces EIP-1087): not started yet
* [ ] [EIP 1234](https://eips.ethereum.org/EIPS/eip-1234) Constantinople difficulty bomb delay and block reward adjustment (difficulty part in ``ethereumjs-block``, see [Byzantium PR](https://github.com/ethereumjs/ethereumjs-block/pull/32) for reference)

**Comment by holgerd77** [comment]
Updated this with the latest changes from the progress tracker (EIP-1087 -> EIP-1283, added EIP-1234 with reference to ``ethereumjs-block`` library).

**Comment by holgerd77** [comment]
Will close in favor of project https://github.com/ethereumjs/ethereumjs-vm/projects/1 and issues for the separate EIPs, then we have more fine-grained EIP implementation discussions.
