### ISSUE TITLE
Improve VM browser compatibilty / test coverage

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#465]
With the merge of #461 there is now browser testing done on the VM to improve VM browser compatibility and avoid introducing bugs like #457.

Currently browser tests are not run on all API test files and many files are excluded since tests were not passing, see [karma.conf.js](https://github.com/ethereumjs/ethereumjs-vm/blob/master/karma.conf.js) ``exclude`` directive.

Excluded tests should be integrated and the underlying issues addressed. Initial experiments indicated that there probably will be some deeper investigation needed and it's probably most practical to address step-by-step on separate PRs. It is also likely that these fixes will spawn over different libraries and not only target the VM, so this should be addressed in a holistic way with PRs where necessary.

The following is a list of the test files which need to be activated:

- [ ] ``./tests/api/state/stateManager.js``
- [x] ``./tests/api/state/storageReader.js``
- [x] ``./tests/api/index.js``
- [x] ``./tests/api/runBlock.js'``
- [x] ``./tests/api/runBlockchain.js``

**Comment by cdetrio** [comment]
It would also be nice to document and test all ethereumjs-vm methods that remix uses. For example, a recent change to `stateManager.checkpoint()` broke remix (though it was easily fixed): https://github.com/ethereum/remix/pull/1103#issuecomment-468050124

**Comment by holgerd77** [comment]
@cdetrio ``StateManager`` is a bit a special case since it is just in the transition from private to public with the API currently marked as experimental.

**Comment by s1na** [comment]
Some of the issues (will update list):

- One of the `stateManager` tests [requires](https://github.com/ethereumjs/ethereumjs-vm/blob/master/tests/api/state/stateManager.js#L127) `ethereumjs-testing` which depends on `asyncawait` which depends on `node-fibers` which doesn't work in browsers.
- In `tests/api/index.js`, runBlockchain calls somewhere `stateManager`s `generateCanonicalGenesis` which puts ~8000 accounts to the trie. This causes the tests to time out (even 200s is not enough).

**Comment by holgerd77** [comment]
For ``ethereumjs-testing`` we probably should revert [asyncawait](https://github.com/ethereumjs/ethereumjs-testing/commit/f19f34b7d488ac0dc0960dec5aeaca4215a678c4) introduction (from October 2017 for Node 6 support) since we have now dropped Node 6.

This will likely cause similar problems in other libraries as well.

**Comment by holgerd77** [comment]
Did a test run for the failing ``StateManager`` browser tests, the ``asyncawait`` removal in ``ethereumjs-testing`` alone doesn't fix the tests yet, will nevertheless do a release for that.

**Comment by holgerd77** [comment]
Re-checked, `StateManager` tests are still excluded in [karma.conf.js](https://github.com/ethereumjs/ethereumjs-vm/blob/master/karma.conf.js) so this needs some analysis if the tests would still fail and eventually some follow-up fixing.

**Comment by ryanio** [comment]
It looks like there are two slow tests in `./tests/api/state/stateManager.js`:

1. `should generate the genesis state correctly`
1.  `should generate correct genesis state root for all chains`

As @s1na commented:

> `generateCanonicalGenesis` puts ~8000 accounts to the trie. This causes the tests to time out (even 200s is not enough).

I couldn't find a timeout that works on my machine to successfully complete the tests. Commenting them out finishes the test suite without any errors.

My proposed solution is to add this code to the beginning of both those tests:

```js
if (window.__karma__) {
  st.skip('skip slow test when running in karma');
  return st.end();
}
```

Let me know if you'd like for me to open a PR with the above.

**Comment by evertonfraga** [comment]
That’s great, @ryanio!

Can you ensure it works with a low amount of accounts, like 800?

**Comment by evertonfraga** [comment]
Doing that of course will generate a different state root hash, might not be worth the trouble.

**Comment by holgerd77** [comment]
I think skipping is easiest, might not be worth the effort, not sure. @ryanio eventually you can do some sort experiment in it but otherwise implement your solution?
