### ISSUE TITLE
Istanbul Hardfork Meta Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#501]
Entry points for information:

- [EIP-1679 Meta EIP](https://eips.ethereum.org/EIPS/eip-1679) (canonical source)
- [EthHub Istanbul Roadmap](https://docs.ethhub.io/ethereum-roadmap/istanbul/)
- [eth.wiki Istanbul Roadmap](https://eth.wiki/en/roadmap/istanbul)
- [GitHub ethereum/pm "Istanbul" search](https://github.com/ethereum/pm/search?q=Istanbul&unscoped_q=Istanbul)

EIP Working List:

- [x] [EIP-152](https://github.com/ethereum/EIPs/pull/2129): Blake 2b `F` precompile
  - [x] VM: Add precompile, #568, PR #584 
  - [x] Common: Update price params, https://github.com/ethereumjs/ethereumjs-common/pull/58
- [x] [EIP-1108](https://eips.ethereum.org/EIPS/eip-1108): Reduce alt_bn128 precompile gas costs
  - [x] Common: Istanbul integration, add updated gas costs, https://github.com/ethereumjs/ethereumjs-common/pull/53
  - [x] VM: Update on new Common version, https://github.com/ethereumjs/ethereumjs-vm/pull/540
- [x] [EIP-1344](https://eips.ethereum.org/EIPS/eip-1344): Add ChainID Opcode
  - [x] VM: Add Opcode, #569, PR #572 
  - [x] Common: Update price params, https://github.com/ethereumjs/ethereumjs-common/pull/58
- [x] [EIP-1884](https://eips.ethereum.org/EIPS/eip-1884): Trie-size-dependent Opcode Repricing
  - [x] VM: Add SELFBALANCE Opcode, #579, PR #581  
- [x] [EIP-2028](https://eips.ethereum.org/EIPS/eip-2028): Calldata Gas Cost Reduction
  - [x] VM: Integrate updated Common object, #570, PR #583  
  - [x] Common: Update price params, https://github.com/ethereumjs/ethereumjs-common/pull/58
- [x] [EIP-2200](https://github.com/ethereum/EIPs/pull/2200): Rebalance net-metered SSTORE gas costs with consideration of SLOAD gas cost change (still the most discussed PR, follow discussion closely, see EIP PR thread or e.g. [this comment](https://gitter.im/ethereum/AllCoreDevs?at=5d5d154a25764a3642d3249f) on ACD Gitter channel)
  - [x] VM: Eventually some of the old `Constantinople` implementation at #367 can be reused, see also tests at #502, PR #590
  - [x] Common: Price updates, https://github.com/ethereumjs/ethereumjs-common/pull/65

Other TODOs:

- [ ] Update [ethereumjs-testing](https://github.com/ethereumjs/ethereumjs-testing) with `Istanbul` tests once substantial test parts are merged, e.g. https://github.com/ethereum/tests/pull/627

We should as time/decisions progresses create separate issues for accepted EIPs and discuss implementation details there.

**Comment by axic** [comment]
On the last ACD call it was decided that https://eips.ethereum.org/EIPS/eip-1679 is the canonical source of information for proposed EIPs. It should be enough to follow that.

**Comment by holgerd77** [comment]
@axic Ah ok, thanks!

**Comment by holgerd77** [comment]
Grabbed this [Istanbul EIP Readiness Checklist](https://docs.google.com/spreadsheets/d/1Mgo7mJ6b6wimUwafsMo1l-b44uec28E_Hq8EQ7YdeEM/edit#gid=0) from the [EIP](https://gitter.im/ethereum/EIPs) Gitter channel, super-detailed and helpful.

Still not 100% sure on the process though and what EIPs will finally be included. As far as I got comments from @bmann on ACD Gitter, there seems to be the need for a reference implementation of an EIP to be included, not sure if there also needs to be a final ok from ACD call and if there is/will be some general limitation in scope at some point to not overload.

I would suggest we start with some low-level stuff from the spreadsheet, this opcode renaming [EIP-1803](https://eips.ethereum.org/EIPS/eip-1803) has made it pretty far and will likely be included, since it wouldn't make sense to postpone such a trivial change.

Will open an issue on that so that we get the process going.

**Comment by holgerd77** [comment]
Truffle/Ganache: @davidmurdoch @benjamincburns
Remix: @yann300 @lianahus 
Others: Please drop a note if you are using the VM in your library in a HF relevant context

We are now starting Istanbul integration, just to let you. I would suggest you follow the process a bit and start early on with a draft integration so that users can early on start to experiment with new features. This will take an important role in helping to prevent such a chaotic last-minute situation as happened during along the last ``Constantinople``/``Petersburg`` hardfork 😛.

We are also very close on merging the ``TypeScript`` transition work from @s1na here #479 into ``master`` and will publish a ``beta`` ``v4`` release on this during next week. This is also coming with heavy internal changes, the outer API stays unchanged though for now. The inner structure is not completely finalized and will likely further change to some extend on the way towards a final release. You are very much invited to have a look, do your thoughts on that and hook into the process.

If you have any questions on ``Istanbul`` respectively ``v4`` let us know! 😄

Cheers
The EthereumJS Team

**Comment by holgerd77** [comment]
Have updated the initial post with a new EIP working list, please check once finished.

**Comment by holgerd77** [comment]
TODO: add [EIP-2200](https://github.com/ethereum/EIPs/pull/2200) and [EIP-1884](https://eips.ethereum.org/EIPS/eip-1884) accepted in ACD [#68](https://github.com/ethereum/pm/pull/120/files) to the list, create separate task issue on the appropriate libraries.

**Comment by holgerd77** [comment]
Solved by #596 and following PRs, will close.
