### ISSUE TITLE
Finishing up for beta and final v4 Releases

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#544]
Finalization issue for the work done towards the v4 release (see [list of merged PRs](https://github.com/ethereumjs/ethereumjs-vm/pulls?q=is%3Apr+is%3Aclosed)), some discussion on this also happening here https://github.com/ethereumjs/ethereumjs-vm/issues/455.

@s1na @alcuadrado Seems we are loosing a bit oversight 😄, can you add all things which still needs to be finished here (directly in this first comment by editing) so that we can finish up on the `v4` release?

## Finalize before beta release

- [x] @s1na: Promisify runBlockchain, runBlock,... APIs [REFERENCE MISSING]

## Finalize before final release

- [x] @holgerd77: Update `ethereumjs-tx` library to `v2.0.0` (TypeScript), in the works here https://github.com/ethereumjs/ethereumjs-vm/pull/541
- [x] @alcuadrado: `ethereumjs-blockchain` issue https://github.com/ethereumjs/ethereumjs-blockchain/issues/114 and TypeScript version update
- [ ] @alcuadrado @s1na: Simplification of return values [REFERENCE MISSING]
- [x] @alcuadrado: Solidity example https://github.com/ethereumjs/ethereumjs-vm/issues/542
- [x] @alcuadrado @holgerd77: Use more flexible Common library regarding chainId respectively generally test network configuration handling, see https://github.com/ethereumjs/ethereumjs-common/issues/54
- [ ] ...

**Comment by holgerd77** [comment]
Update: have extended this a bit to also include finalization todos for the final release. If the list above gets to extensive we can also very well go through 2-3 beta releases if we find appropriate and/or better fitting.

**Comment by holgerd77** [comment]
@s1na @alcuadrado After having compiled down the release notes https://github.com/ethereumjs/ethereumjs-vm/pull/547 I think we can very well do the beta release on Wednesday and leave the other points from above for either a subsequent beta release or the final release. Nothing seems so substantial to me to really need a further delay and I think its also good to get something out to reduce the psychological burden of further collecting stuff and make things bigger and bigger. 😛

What do you guys think? If you've got some last minute work on Monday or so (Tuesday maybe not) feel free to do.

Cheers
Holger

**Comment by s1na** [comment]
@holgerd77 Thanks for compiling the comprehensive release notes! I think that makes sense. I would still like to add some documentation (specially to the re-structured code), and my personal preference would have been to improve the naming (of `Loop` and `Interpreter` which I've grown to hate :smile:) before the release. I would appreciate some brainstorming on this as I'm not the best at naming stuff. But I guess these could also be done in subsequent `beta` or the final release as well.

**Comment by holgerd77** [comment]
Gna, no hurry, then let's do the first `beta` earliest mid next week, more important that everyone feels comfortable with the changes (especially you who has done most of the work). 😄

**Comment by s1na** [comment]
Ah no I didn't mean to stall the release. What I meant was, let's keep Wednesday as the target, and I will try to add some docs before that (hopefully) and if I couldn't make it, well, it will go to subsequent releases :)

**Comment by holgerd77** [comment]
Really not sure on this myself. The docs should be relatively consistent also for the beta release, and we should also have this renaming done, otherwise it get's confusing if we switch in-between for such central components, otherwise it also get's confusing to have these old names around in the release notes since most people will refer to these initial release notes as primary what's-changed notes.

Let's see if we get some progress on these two things during next 24-36 hours, otherwise we might want to do rather next week.

**Comment by alcuadrado** [comment]
> * [ ]  @alcuadrado @s1na: Simplification of return values [REFERENCE MISSING]
> *

This is about simplifying `ExecResult`, which was discussed in this PR: https://github.com/ethereumjs/ethereumjs-vm/pull/529

I'll give it a try. Will probably get back with lots of questions :)

**Comment by holgerd77** [comment]
Closed by #571
