### ISSUE TITLE
VM v5 Release Planning

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#681]
Now with the monorepo transition being in its latests phases we can start on planning the next major VM release, various things are on the door for this. I'll try to collect here what I can think of and we can further discuss, if we have some agreement on further additions please just add to the list below:

### TODO List

- [x] `VM`: Init method to prevent race conditions PR #665 by @rumkin, review/merge , @evertonfraga 
- [x] `VM`: Opcode refactor PR #664 by @rumkin, review/merge, @cgewecke, @alcuadrado 
- [x] `VM`: Integrate `Block` `v3.0.0` and new `Blockchain` versions, @evertonfraga 
  - [x] `Block` library TypeScript `v3.0.0` (see https://github.com/ethereumjs/ethereumjs-block/pull/74, work already done, just needs release PR + npm publishing), PR #682, @evertonfraga 
  - [x] `Blockchain`: Integrate `Block` `v3.0.0`, promisified `Blockchain` version #833 , @evertonfraga @ryanio 
- [x] `VM`: Integrate MPT release [v4.0.0](https://github.com/ethereumjs/merkle-patricia-tree/pull/111), @ryanio, PR #787 
  - [x] `Block`: integrate into `Block` library - eventually along `v3.0.0` #682, @evertonfraga 
  - [x] `Account`: eventually integrate into `Account` library (`devDependencies` for tests), @ryanio, update: dependency removed, PR #787
- [x] `VM`: Extract the [state manager](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/vm/lib/state) to have its own package, see [section](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/vm#statemanger) in VM README for context, @ryanio, update: decided (missing reference, can't find) to keep it integrated for now
  - [x] Integrate promises into StateManager, #719 
  - [x] Add Interface for StateManager, #763 
- [x] `All`: Update `ethereumjs-util` to `v7.0.2`, #748 (double-check if all occurences updated!)
- [ ] `All`: Update to a a new `ethereumjs-config` version integrating e.g. https://github.com/ethereumjs/ethereumjs-config/pull/28 (ES2017 build target, separate browser build)
- [ ] Analyze and fix speed deterioration of MPT v4 library, see https://github.com/ethereumjs/merkle-patricia-tree/issues/124, @ryanio 
  - [ ] Add simple benchmarking tool to VM, PR #794, @s1na, @ryanio, @holgerd77 
  - [ ] Run benchmarks on pre-deteriorated, post-deteriorated and fixed MPT and compare
  - [ ] Compare with MPTs own [benchmarks](https://github.com/ethereumjs/merkle-patricia-tree/tree/master/benchmarks) and see if consistent
- [x] Finish all Hardfork backports for VM, @jochem-brouwer 
  - [x] SpuriousDragon HF support, #791, @holgerd77 
  - [x] TangerineWhistle HF support, #807, @holgerd77, @jochem-brouwer 
  - [x] Finalize and review Homestead support PR, #815, @jochem-brouwer, all
  - [x] Finalize and review chainstart (Frontier) support PR, #828, @jochem-brouwer, all
  - [ ] Optional but nice (shouldn't bee too much extra work and then we are really complete): add DAO HF, all
- [x] Add Berlin HF EIPs
  - [x] ~Finalize and review BLS precompile EIP PR, #785, @jochem, all~ -> Postponed/skipped on release due to EIP HF integration uncertainties due to [EVM384](https://github.com/ethereum/pm/issues/200#issuecomment-678232436) alternative proposal
  - [x] Review, eventually finalize subroutine EIP PR, #754, @cgewecke, all 
- [ ] Set VM default HF to `Istanbul` (`MuirGlacier` is problematic since not available on all testnets (e.g. `Rinkeby` which would lead to unexpected behavior if people just change the network without further thinking about this (which is likely))

Be Happy! 🦄  😄  🌻

### Discussion

- ~`VM`: Do we finally want to expose the reworked `Interpreter` API Sina @s1na introduced along the [v4.0.0 release](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/v4.0.0-beta.1) ( see "EVM Modularization and Structural Refactoring" section as well as linked PR within the section)?~ Related: #636 
  - Update: agreement that there is currently still too much movement around this, so won't be integrated in `v5` but rather postponed to a subsequent major version release
- ~`VM`, `merkle-patricia-tree`: Do we want to also wait for the TypeScript / Promisification v4.0.0 release of the merkle tree library to add here or do we want to give this a bit more time (this would also need an update on the `Block` and eventually the `Account` (only dev dependency) library)? @ryanio~ 
  - -> Update: MPT release is imminent, so this can be integrated, have moved to `TODO`

### Notes

1. `Ownership`: I've assigned team members already involved or I thought fitting to the tasks, if you can't/don't want to take over just replace with OPEN or something.

2. `Date`: Just as some orientation, I would roughly target a date within a range of 2-3 weeks for a possible release, let's take **April 22, Wednesday** as a starter, let me know if you have comments on that

**Anything else? Something missing? Other suggestions?**

**Comment by holgerd77** [comment]
Just some notes, before I forget, will work this better into the description above and generally update the issue list early next week.

- Work here turns out to be likely to extensive to match the April 22 date in a couple of days, we'll likely have to move here by at least I would say 2 weeks
- MPT promisification PR by @ryanio is merged (yeah 🎉, great work) and a v4 release is relatively imminent https://github.com/ethereumjs/merkle-patricia-tree/pull/111, so we can likely take a MPT update in
- @cgewecke has committed to do some work on the `ethereumjs-util` library and finalize https://github.com/ethereumjs/ethereumjs-util/pull/228, wonder if we should also take this in (would be also a major release on the `util` library) since this would significantly improve the installation process, which is currently really a pain regarding the crypto packages and source for many complaints. Not sure, Chris will you be able to work on this relatively soon (next week optimally?)?

We generally have to look at the dependency tree (by @evertonfraga) really closely regarding all these things to not miss some updates.

**Comment by cgewecke** [comment]
> Chris will you be able to work on this relatively soon (next week optimally?)?

@holgerd77 Yes, I will start working on this Monday, April 22.

**Comment by kumavis** [comment]
some ideas from earlier days of `ethereumjs-*`
- `merkle-patricia-tree` if you make getting the current state root of a merkle-patricia-tree an async op, you can put off ALL hash calculations for new values until the root is read. if the root is never read, you saved yourself a bunch of work
- `vm` if you make the storage backend easily pluggable, you can run the vm off of rpc requests 
https://github.com/ethereumjs/ethereumjs-vm/blob/0f10fcfdbc55ceadbff6adeb54bca6df393ef62f/lib/hooked.js#L77-L83 This is hugely useful for anyone who wants to run the vm while accessing state remotely. sad to see support for it was dropped.

basicaclly scifi:
- `vm`: out-of-order execution. (not speculative execution or branch prediction) a significant change, but if you make all values you push onto the stack to be promises, you get great perf wins like parallel storage reads (huge for zero and light clients), and you let the js engine figure out the causality requirements. to really do it correctly you need to build a funky mutex machine around memory read/writes, but it sounds like a fun challenge.

**Comment by kumavis** [comment]
worth noting that ganache's forked blockchain feature also uses a json rpc client for state reads, this is how they are hooking in https://github.com/trufflesuite/ganache-core/blob/a5f43a4d666c82bce9da51f9ce1d15b6561e24f3/lib/utils/forkedblockchain.js#L89-L93

this usecase should be supported without having to override underscored properties/methods

**Comment by s1na** [comment]
Wrote down some thoughts re making `EVM` (`Interpreter` and `EEI`) public [here](https://github.com/ethereumjs/ethereumjs-vm/issues/636#issuecomment-620647613). Probably makes sense to keep them private for this release.

**Comment by holgerd77** [comment]
For notice: have substantially updated the initial TODO list here to keep track with our latest discussions around various questions.

**Comment by holgerd77** [comment]
@evertonfraga Can you please give the TODO list from above an update, so that things won't get forgotten?

One additional thing which comes to my mind: we should do a last

```shell
npm ls ethereumjs-util
```

check on the final VM version to ensure that we haven't forgotten anything along the Uti v7 update.

Also: @ryanio what is the state of the MPT v4 update? Can we still manage to get this in?

**Comment by evertonfraga** [comment]
@holgerd77 sure. I will change the todo descriptions, if you don’t mind.

**Comment by ryanio** [comment]
@holgerd77 yes let's release mpt v4 on npm and i will finish my branch to include :)

**Comment by alcuadrado** [comment]
> One additional thing which comes to my mind: we should do a last
> 
> ```shell
> npm ls ethereumjs-util
> ```
> 
> check on the final VM version to ensure that we haven't forgotten anything along the Uti v7 update.

I think this should be checked by a linter/script on the CI. I have a script to do this in Buidler, I hadn't proposed importing it here before, because it works with a monorepo. I'll open a PR now.

**Comment by evertonfraga** [comment]
Thanks @alcuadrado!

**Comment by alcuadrado** [comment]
Can we release and use `@ethereumjs/config-typescript` before this version gets published?

**Comment by evertonfraga** [comment]
Sure @alcuadrado, that’s on my plan. To make things more clear, tomorrow I’ll start the day creating a milestone with all the issues for the v5. You all will be welcome to suggest as well.

**Comment by jochem-brouwer** [comment]
Some thoughts on what I think should be included in V5 (as addition to things already mentioned here):

- Berlin HF support 
- Support for all older HFs (we could skip `DAO` for now though)
- Remove callbacks from `blockchain` (blockchain is the only package which is now using callbacks as opposed to all other packages having replaced the callbacks by async functions).

**Comment by holgerd77** [comment]
Have updated the TODO list from above so that we can finally close in on a release, please add if something is missing.

**Comment by alcuadrado** [comment]
How is the Berlin support gonna be released? I think it should be somehow marked as experimental, with no guarantees of stability, as Berlin may include a different set of eips. Did we have some experimental apis before? 

Just curious, I don't think this requieres too much thinking, just not making it default and a big warning.

**Comment by holgerd77** [comment]
@alcuadrado Yes, a bit as you described. Analogous to the previous forks we won't switch the default fork yet and mark the HF support as experimental. Once this has finalized we will likely release a new minor version with the stable-marked HF (still not made default). This worked pretty well in the past, no complains there at any time.

**Comment by alcuadrado** [comment]
Oh, that's nice. I thought the previous HFs were released after they were settled/activated.

**Comment by holgerd77** [comment]
Closed in favor of #907
