### ISSUE TITLE
Archive original monorepo projects in GitHub

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#688]
Archive repositories

- [x] [ethereumjs-account](https://github.com/ethereumjs/ethereumjs-account)
  - [x] transferred issues to VM + re-applied all their labels
  - [x] changed package description and URL pointing to VM's
  - [x] added badge notice in README
  - [x] archive repo
- [x] [ethereumjs-block](https://github.com/ethereumjs/ethereumjs-block)
  - [x] transferred issues to VM + re-applied all their labels
  - [x] changed package description and URL pointing to VM's
  - [x] added badge notice in README
  - [x] archive repo
- [x] [ethereumjs-blockchain](https://github.com/ethereumjs/ethereumjs-blockchain)
  - [x] transferred issues to VM + re-applied all their labels
  - [x] changed package description and URL pointing to VM's
  - [x] added badge notice in README
  - [x] archive repo
- [x] [ethereumjs-common](https://github.com/ethereumjs/ethereumjs-common)
  - [x] transferred issues to VM + re-applied all their labels
  - [x] changed package description and URL pointing to VM's
  - [x] added badge notice in README
  - [x] archive repo
- [x] [ethereumjs-tx](https://github.com/ethereumjs/ethereumjs-tx)
  - [x] transferred issues to VM + re-applied all their labels
  - [x] changed package description and URL pointing to VM's
  - [x] closed PRs
  - [x] added badge notice in README
  - [x] archive repo

**Comment by evertonfraga** [comment]
Repositories are now archived. I was careful with the wording used and made a _special badge_ for those archived repos, for eternity 😄 

<p align="center">
  <a href="https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/tx">
    <img src="https://user-images.githubusercontent.com/47108/78554503-42c47000-77d9-11ea-8935-2d93981d50df.png" width="309">
  </a>
</p>


![image](https://user-images.githubusercontent.com/47108/78560663-6b9e3280-77e4-11ea-9509-547d6e0676db.png)

**Comment by holgerd77** [comment]
Love the badge! 😄

Had a short look on all the repos, everything looks good here on first sight! 👍 Thanks for doing these work-intensive need-to-be-done tasks.

**Comment by evertonfraga** [comment]
Thanks! Here's another badge I made for the deprecated pkgs. 

<p align="center">
  <img src="https://user-images.githubusercontent.com/47108/78584022-99e03a00-7805-11ea-9a30-a049387c3aa9.png" width="309">
</p>
