### ISSUE TITLE
VM v5 Release Preparation and Process

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#907]
Follow-up issue on #681, will close there since issue is over-used and gotten clustered over time, still valuable reference though.

We are closing in on the release of VM v5 and related libraries into the `@ethereumjs/[LIBRARY_NAME]` namespace with several major releases. This issue is to keep track on the last to be applied changes and follow up on the process.

### Procedure

Suggested procedure is to do a `beta` release series mid or end next week (CW42), then collect feedback and either follow up with a second beta - eventually RCs (to be decided on the nature of the feedback received) and target the final releases for two weeks later (CW44).

- Beta Releases for CW42 (Oct 12-18)
- Final Releases for CW44 (Oct 26 - Nov 1)

### Remaining TODOs

- [x] The `ethereumjs-config` `v2.0` update, #886 , @evertonfraga 
- [x] The block  refactor, #883 , @ryanio, eventually @jochem-brouwer 
- [x] Integrate the new `Util.Account` class from the work on https://github.com/ethereumjs/ethereumjs-util/pull/275 by @ryanio, #911 
  - [x] Remove all remaining code dependencies from the monorepo, integrate new `Util` `Account` class, @ryanio 
  - [x] Remove the account package from `packages`, remove CI integrations, @ryanio 
- [x] Integrate new `Util.Address` class from the work on https://github.com/ethereumjs/ethereumjs-util/pull/186 by @s1na and @ryanio, @ryanio
- [x] Final `defineProperties` removal check, follow-up PRs (candidate to somewhat postpone release process), @ryanio 
- [x] Short exchange on the source map question would likely make sense, #902 -> Decided to be optional respectively non-blocking for the release process (eventually integrate after `dev` releases)
- [x] Integrate new build process (ES2017/browser builds) from https://github.com/ethereumjs/ethereumjs-config/pull/28 (PR by @ryanio), @cgewecke, #921 

#### Process Checklist

0. Work down package [dependency graph](https://github.com/ethereumjs/ethereumjs-vm#package-dependency-relationship) on releases, start with `Common`
1. Update CHANGELOG on completeness adding missing PRs merged since latest release date
2. Bump version in `package.json`, bump monorepo versions of all `dependencies` and `devDependencies` to released versions, **on final releases re-introduce caret ^ dependency range!**
3. Update the respective `README` from package folder to match to be released version
4. Rebuild documentation
5. Run linting
6. Check diff
7. Commit everything
8. Take a breath. 🌿 🌻  🐹
9. Go to 0., repeat for all packages

=> Push. Review. Merge.

0. Work down package [dependency graph](https://github.com/ethereumjs/ethereumjs-vm#package-dependency-relationship) on releases, start with `Common`
1. Build locally, one final test run, check package contents with `npm pack`
2. Release from `package` folders manually with `npm publish [--tag beta]` (`latest` tag replacement: on non-final releases (`beta`, `rc`,...), exception: first round of scoped package releases)
3. Check everything on the respective `npm` package site
7. Add release on GitHub:
  - Tag e.g. `@ethereumjs/common@2.0.0-beta.1` towards `master`
  - Title e.g. `@ethereumjs/common v2.0.0-beta.1`
  - CHANGELOG description from the raw `CHANGELOG.md`, add `beta` header
  - Mark as `pre-release`!!!
8. Take a breath. 🌿 🌻  🐹
9. Go to 0., repeat for all packages

#### Release Checklist

Will take the current `npm` packages as main links.

- [x] [VM](https://www.npmjs.com/package/ethereumjs-vm) `ethereumjs-vm` `v4.2.0` -> `@ethereumjs/vm` `v5.0.0`
  - [x] `v5.0.0-beta.1` Release
  - [x] `v5.0.0-beta.2` Release
  - [x] `v5.0.0-rc.1` Release
  - [x] `v5.0.0` Release
- [x] [Block](https://www.npmjs.com/package/ethereumjs-block) `ethereumjs-block` `v2.2.2` -> `@ethereumjs/block` `v3.0.0`
  - [x] `v3.0.0-beta.1` Release
  - [x] `v3.0.0-beta.2` Release
  - [x] `v3.0.0-rc.1` Release
  - [x] `v3.0.0` Release
- [x] [Blockchain](https://www.npmjs.com/package/ethereumjs-blockchain) `ethereumjs-blockchain` `v4.0.4` -> `@ethereumjs/blockchain` `v5.0.0`
  - [x] `v5.0.0-beta.1` Release
  - [x] `v5.0.0-beta.2` Release
  - [x] `v5.0.0-rc.1` Release
  - [x] `v5.0.0` Release
- [x] [Common](https://www.npmjs.com/package/ethereumjs-common) `ethereumjs-common` `v1.5.2` -> `@ethereumjs/common` `v2.0.0`
  - [x] `v2.0.0-beta.1` Release
  - [x] `v2.0.0-beta.2` Release
  - [x] `v2.0.0-rc.1` Release
  - [x] `v2.0.0` Release
- [x] [Ethash](https://www.npmjs.com/package/ethashjs) `ethashjs` `v0.0.8` -> `@ethereumjs/ethash` `v1.0.0`
  - [x] `v1.0.0-beta.1` Release
  - [x] No `beta.2` release planned
  - [x] `v1.0.0-rc.1` Release
  - [x] `v1.0.0` Release
- [x] [Tx](https://www.npmjs.com/package/ethereumjs-tx) `ethereumjs-tx` `v2.1.2` -> `@ethereumjs/tx` `v3.0.0`
  - [x] `v3.0.0-beta.1` Release
  - [x] `v3.0.0-beta.2` Release
  - [x] `v3.0.0-rc.1` Release
  - [x] `v3.0.0` Release

🍀

**Comment by holgerd77** [comment]
Closed by #962
