### ISSUE TITLE
Client TODOs: Tracking Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#975]
Tracking issue for various TODOs related to the client, can be worked along other PRs:

- [x] `packages/client/test/integration/lightsync.spec.ts` -> 'should not sync with stale peers' test throws unhandled promise rejection warning, see [comment](https://github.com/ethereumjs/ethereumjs-vm/issues/975#issuecomment-737456865) below, PR https://github.com/ethereumjs/ethereumjs-vm/pull/1006
- [x] 'could not find a declaration file' errors in `packages/client/browser/libp2pnode.ts`, `packages/client/lib/net/peer/libp2ppeer.ts`, `packages/client/lib/net/protocol/libp2psender.ts` (currently disguised with `@ts-ignore` directives), PR https://github.com/ethereumjs/ethereumjs-vm/pull/1008
- [x] Remove `package-lock.json` from devp2p and client `.gitignore` files, generally audit rest of gitignores, see [comment](https://github.com/ethereumjs/ethereumjs-vm/issues/975#issuecomment-737466555) below, PR https://github.com/ethereumjs/ethereumjs-vm/pull/1009
- [x] Find a more type safe way of dynamically adding methods in `BoundProtocol`, see [TODO note](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/client/lib/net/protocol/boundprotocol.ts#L167-L168), see [comment](https://github.com/ethereumjs/ethereumjs-vm/issues/975#issuecomment-739034213) below, PR #1010

**Comment by ryanio** [comment]
I just looked into the lightsync integration test unhandled promise rejection warning.

We need a catch clause in `boundProtocol.addMethods()` here: https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/client/lib/net/protocol/boundprotocol.ts#L170

can be as simple as:

```this.request(name, args).catch((error: Error) => { this.emit('error', error) }```

however then I got this unhandled promise error:

```
(node:49314) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at FullSynchronizer.latest (/Users/ryanghods/dev/ethereumjs-vm/packages/client/lib/sync/fullsync.ts:84:19)
    at FullSynchronizer.syncWithPeer (/Users/ryanghods/dev/ethereumjs-vm/packages/client/lib/sync/fullsync.ts:94:20)
    at FullSynchronizer.start (/Users/ryanghods/dev/ethereumjs-vm/packages/client/lib/sync/sync.ts:97:24)
```

which is weird because in `sync.start()` the `await sync()` is already in a try catch block, so i'm not sure why it's not catching it. as a test i put a catch clause on the promise directly and that did catch it, so i'm scratching my head a bit.

**Comment by ryanio** [comment]
another issue to consider is that I think we need to remove `package-lock.json` from both the devp2p and client `.gitignore`

although we use hoisting, in the past sometimes lerna puts dependencies used only by those packages in their own directory. i've also seen lerna hoist those to root as well though so i'm not sure what today's behavior is, but it would be safer to not have them ignored.

there may be some benefit to audit and dedupe the rest of the gitignores too, devp2p and client are pretty long and the more generalized stuff can probably be brought to the root gitignore.

**Comment by ryanio** [comment]
For another item I think it would be good to find a better pattern of dynamically adding methods in BoundProtocol ([as per this todo note](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/client/lib/net/protocol/boundprotocol.ts#L167-L168)) as it would fix a lot of `as any` overrides currently in the ts code.

**Comment by ryanio** [comment]
All items in this issue have been resolved. 🎉
